### ISSUE TITLE
构造过程章节有内容上下对不上

### ISSUE THREAD

**Issue by allanGoldZhiKang** [SwiftGGTeam/the-swift-programming-language-in-chinese#979]
规则 1
    如果子类没有定义任何指定构造器，它将自动继承父类所有的指定构造器。

因为它为自己引入的所有属性都提供了默认值，并且自己没有定义任何构造器，ShoppingListItem 将自动继承所有父类中的指定构造器和便利构造器。

**Comment by numbbbbb** [comment]
原文：

Rule 1
If your subclass doesn’t define any designated initializers, it automatically inherits all of its superclass designated initializers.

Because it provides a default value for all of the properties it introduces and does not define any initializers itself, ShoppingListItem automatically inherits all of the designated and convenience initializers from its superclass.

看起来是苹果不太严谨。
